### common variables
@username=api_user
@password=DMTinf#2023


### Get json save request to file no auth

POST https://localhost:3443/api/secure/json
content-type: application/json
Authorization: Basic a b

{    
}

### Get json save request to file with auth

POST https://localhost:3443/api/secure/json
content-type: application/json
Authorization: Basic {{username}} {{password}}
SAP-Client: 300

{    
}